// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3luJ9DDfunuv6nP1Z_ueoVM3SuTJTGs',
    appId: '1:694730752148:web:c9de84167bf3100e0df481',
    messagingSenderId: '694730752148',
    projectId: 'movie-app-31b60',
    authDomain: 'movie-app-31b60.firebaseapp.com',
    storageBucket: 'movie-app-31b60.appspot.com',
    measurementId: 'G-Z2PL3LW1BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPgjMwq0Cl7QEKyb0hn7UjJJSLMMNy9U',
    appId: '1:694730752148:android:83193f16851e84dc0df481',
    messagingSenderId: '694730752148',
    projectId: 'movie-app-31b60',
    storageBucket: 'movie-app-31b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuc-D-vd_P3rS8TKECSYmFFDi8RHamYeg',
    appId: '1:694730752148:ios:7c67a98fd950b6840df481',
    messagingSenderId: '694730752148',
    projectId: 'movie-app-31b60',
    storageBucket: 'movie-app-31b60.appspot.com',
    iosClientId: '694730752148-8lg5fjfd8rf9bgpu8ie6sf0tnktime2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuc-D-vd_P3rS8TKECSYmFFDi8RHamYeg',
    appId: '1:694730752148:ios:793238020892e8e90df481',
    messagingSenderId: '694730752148',
    projectId: 'movie-app-31b60',
    storageBucket: 'movie-app-31b60.appspot.com',
    iosClientId: '694730752148-ulk10r09mm7p7r66dbadtlpim4j9jajb.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
